sudo: false

notifications:
  email: false

language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.phive

matrix:
  include:
    - php: 7.2

script:
  - printf 'y\ny\ny\ny\ny\n' | php phive.phar update --prefer-offline
  - php composer.phar update
  - php composer.phar check
