sudo: false

notifications:
  email: false

language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2

script:
  # Fetch gpg keys for phive, php-cs-fixer, php-coveralls, phpunit, phpstan, composer-require-checker
  - gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x9D8A98B29B2D5D79
  - gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xE82B2FB314E9906E
  - gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x4AA394086372C20A
  - gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x8E730BA25823D8B5
  - gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xD2CCAC42F6295E7D
  - gpg --keyserver hkps.pool.sks-keyservers.net  --recv-keys 0x9B2D5D79
  - php phive.phar install
  - ls -la
  - php composer.phar check
